curl -X POST http://localhost:3000/forfaits \
-H "Content-Type: application/json" \
-d '{"idService":1,"nomForfait":"Premium","prixForfait":99.99,"descriptionForfait":"Full service"}'

curl -X GET http://localhost:3000/forfaits

curl -X PUT http://localhost:3000/forfaits/1 \
-H "Content-Type: application/json" \
-d '{"idService":1,"nomForfait":"VIP","prixForfait":120,"descriptionForfait":"Top"}'

curl -X DELETE http://localhost:3000/forfaits/1