curl -X POST http://localhost:3000/employes/addEmploye `
-H "Content-Type: application/json" `
-d '{"role":"admin","nom":"Freaky","prenom":"Gab","courriel":"admin@bellevibe.com","telephone":"4501234567","adresse":"123 1e Avenue","codePostal":"A1A 1A1","mdp":"123456789"}'

curl -X PUT http://localhost:3000/employes/adminEdit/1
-H "Content-Type: application/json"
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzczOTQ3NTQzLCJleHAiOjE3NzM5NTQ3NDN9.S-Moq1QTw0Ps8IpWU6Pk_-5z0FFJyKM3R4NoQ9JlItI"
-d '{"role":"commis", "statut":"actif", "mdp":"123456789"}'

curl -X POST http://localhost:3000/employes/login `
-H "Content-Type: application/json" `
-d '{"email": "admin@bellevibe.com", "mdp": "123456789"}'